### ISSUE TITLE
Hello, I have a question.

### ISSUE THREAD

**Issue by jeonghs9** [hahashu/TextileNet#2]
hello. I downloaded 200,000 images through the Google Drive you uploaded. However, the remaining 500,000 pieces of data were needed, so they were being downloaded using an additional data code. However, an hour after the "Start downloading files for test data..." message appears, the error appears. Is there any other way to download the remaining 500,000 additional data? I need a total of 760,000 image data. Help me.

**Comment by hahashu** [comment]
Hi,  I'll have a look during the weekend

**Comment by hahashu** [comment]
Hi, thanks for the question.
I guess some of the URLs are broken since last time I have downloaded them. I've added a try clause to handle the exceptions in the download function, think it should work now. Thanks.

**Comment by jeonghs9** [comment]
Thank you so much for your help! Let's try!

**Comment by LAVANYA-M2913** [comment]
how to resolve this issue while training the train_resnet.py file 
(textilenet) D:\Project\Dataset\TextileNet-main\src>python train_resnet.py --data fibre --batch_size 512 --num_classes 3
3 --num_workers 32 --seed 0
Train Data Path: fibre\train
Test Data Path: fibre\test
C:\Users\mlava\anaconda3\envs\textilenet\lib\site-packages\torch\utils\data\dataloader.py:557: UserWarning: This DataLoader will create 32 worker processes in total. Our suggested max number of worker in current system is 8 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Number of devices: 0

Epoch: 0
Train Data Path: fibre\train
Test Data Path: fibre\test
C:\Users\mlava\anaconda3\envs\textilenet\lib\site-packages\torch\utils\data\dataloader.py:557: UserWarning: This DataLoader will create 32 worker processes in total. Our suggested max number of worker in current system is 8 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Number of devices: 0

Epoch: 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\mlava\anaconda3\envs\textilenet\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\mlava\anaconda3\envs\textilenet\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\mlava\anaconda3\envs\textilenet\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\mlava\anaconda3\envs\textilenet\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\mlava\anaconda3\envs\textilenet\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\mlava\anaconda3\envs\textilenet\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\mlava\anaconda3\envs\textilenet\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Project\Dataset\TextileNet-main\src\train_resnet.py", line 254, in <module>
    train(epoch)
  File "D:\Project\Dataset\TextileNet-main\src\train_resnet.py", line 186, in train
    for batch_idx, (inputs, targets) in enumerate(train_loader):
  File "C:\Users\mlava\anaconda3\envs\textilenet\lib\site-packages\torch\utils\data\dataloader.py", line 440, in __iter__
    return self._get_iterator()
  File "C:\Users\mlava\anaconda3\envs\textilenet\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\mlava\anaconda3\envs\textilenet\lib\site-packages\torch\utils\data\dataloader.py", line 1038, in __init__
    w.start()
  File "C:\Users\mlava\anaconda3\envs\textilenet\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\mlava\anaconda3\envs\textilenet\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\mlava\anaconda3\envs\textilenet\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\mlava\anaconda3\envs\textilenet\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\mlava\anaconda3\envs\textilenet\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\mlava\anaconda3\envs\textilenet\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
